spring:
  mail:
    username: ${MAIL_USERNAME}
    port: '587'
    properties:
      mail:
        stmp:
          atuh: 'true'
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
    host: ${MAIL_URL}
    password: ${MAIL_PASSWORD}

weatherbeaconboard:
  mail:
    from: weatherbeaconboard@gmail.com

#LOCALHOST
#server:
#  port: 8082

server:
  port: 5000