spring:
  jpa:
    hibernate:
      #TODO: swap with validate when deploying
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
        #Set to true for local testing
        show_sql: true
    open-in-view: 'false'

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

weatherbeaconboard:
  notification:
    base-url: http://localhost:8082
    sendEmail: /v1/sendEmail

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: http://localhost:8081/swagger-ui.html