spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: 'true'
        #Set to true for local testing
        show_sql: false
    open-in-view: 'false'

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

weatherbeaconboard:
  notification:
    #LOCALHOST
    #base-url: http://localhost:8082
    base-url: ${NOTIFICATIONS_URL}
    sendEmail: /v1/sendEmail

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      notificationServiceSendRegistrationEmail:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  bulkhead:
    instances:
      notificationServiceSendRegistrationEmail:
        maxConcurrentCalls: 20
        maxWaitDuration: 0
  ratelimiter:
    instances:
      notificationService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
        registerHealthIndicator: true
  retry:
    instances:
      notificationService:
        maxAttempts: 5
        waitDuration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
